---

- name: Install environment file with system-wide variables
  become: true
  ansible.builtin.template:
    src: environment/environment
    dest: /etc/environment
    mode: 0644
  tags: environment
