---

- name: Set login shell to fish
  become: yes
  user:
    name: "{{ item }}"
    shell: /usr/bin/fish
  loop:
    - root
    - "{{ workstation_user }}"
  tags: fish

- name: Disable fish greeting
  become: yes
  copy:
    src: fish/disable_greeting.fish
    dest: /etc/fish/conf.d/disable_greeting.fish
    mode: 0644
  tags: fish

- name: Install ip function for colored output
  become: yes
  copy:
    src: fish/ip.fish
    dest: /etc/fish/functions/ip.fish
    mode: 0644
  tags: fish

- name: Enable fzf key bindings
  become: yes
  copy:
    src: fish/enable_fzf_key_bindings.fish
    dest: /etc/fish/conf.d/enable_fzf_key_bindings.fish
    mode: 0644
  tags: fish
