---

- name: Set login shell to fish
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /usr/bin/fish
  loop:
    - root
    - "{{ workstation_user }}"
  tags: fish

- name: Disable fish greeting
  become: true
  ansible.builtin.template:
    src: fish/disable_greeting.fish
    dest: /etc/fish/conf.d/disable_greeting.fish
    mode: 0644
  tags: fish

- name: Create ~/.local/bin folder
  become: false
  ansible.builtin.file:
    path: "/home/{{ workstation_user }}/.local/bin"
    state: directory
    mode: 0755
  tags: fish

- name: Add config to prepend ~/.local/bin to PATH
  become: true
  ansible.builtin.template:
    src: fish/add_local_path.fish
    dest: /etc/fish/conf.d/add_local_path.fish
    mode: 0644
  tags: fish

- name: Install ip function for colored output
  become: true
  ansible.builtin.template:
    src: fish/ip.fish
    dest: /etc/fish/functions/ip.fish
    mode: 0644
  tags: fish

- name: Enable fzf key bindings
  become: true
  ansible.builtin.template:
    src: fish/enable_fzf_key_bindings.fish
    dest: /etc/fish/conf.d/enable_fzf_key_bindings.fish
    mode: 0644
  tags: fish
