---

- name: Install .gitconfig file
  become: false
  ansible.builtin.template:
    src: git/gitconfig
    dest: "/home/{{ workstation_user }}/.gitconfig"
    mode: "0644"
  tags: git

- name: Ensure base directory for repository collection exists
  become: false
  ansible.builtin.file:
    path: "{{ workstation_git_collection_dir }}"
    state: directory
    mode: "0755"
  tags: git
